#!/usr/bin/perl -w

=head1 NAME

davpack

=head1 SYNOPSIS

  $ cd pack
  $ cd 49t1_tot2nvmassweno.03.IMPIIFC2018.x
  $ davpack                                   # Create & run new test case
  $ davpack --reuse                           # Rerun last test case
  $ davpack --status                          # See status of last test tasks
  $ davpack --cancel                          # Cancel already submitted tasks

=head1 DESCRIPTION

Run DAVAI test suite from within a pack. 

=head1 DETAILS

This script will :

=over 4

=item 

Create the DAVAI test case and initialize the CIBOULAI interface.

=item 

Compile the executables required for DAVAI.

=item 

Check for other packs (single precision, bound checking) if enabled in the DAVAI configuration

=item 

Create the required symbolic links so that DAVAI can use the executables

=item 

Start the DAVAI test suite

=back

Once the DAVAI tasks have ended, davpack will provide a short report for each of the tasks.

=head1 OPTIONS

=over 4

=item --dryrun

Do everything, but do not start DAVAI test suite.

=item --reuse

Reuse last DAVAI test case.

=item --status

Show status of DAVAI tasks.

=item --cancel

Cancel tasks (with scancel) for last test case.

=item --version

Version of DAVAI tests. We try to guess the version from the cycle, but you may have 
to provide it yourself.

=back

=head1 CONFIGURATION

You need to provide a ~/.davai_profile. In this file, please provide the shell commands
which will enable DAVAI; for instance, on belenos/taranis : 

  module use ~mary/public/modulefiles 
  module load git/2.27.0
  module load python/3.7.6 
  module load davai

This file will be used by davpack to enable DAVAI environment before issuing DAVAI commands.

=head1 REQUIREMENTS

=over 4

=item davai

=item gmkpack

=item gitpack

=back

=head1 SEE ALSO

C<gmkpack>, C<DAVAI>

=head1 AUTHOR

pmarguinaud@hotmail.com

=cut

use strict;
use local::lib;
use Cwd;
use FileHandle;
use File::Path;
use File::Basename;
use Data::Dumper;
use Getopt::Long;
use JSON;
use Storable;
use POSIX qw (strftime);
use File::stat;
use File::Find;
use File::Copy;
use File::Spec;
use Term::ANSIColor;

use FindBin qw ($Bin);
use lib "$Bin/lib";
use bt;
use davai;
use davai::build;

my $HOME = (getpwuid ($>))[7];

sub runCommand
{
  my %args = @_;
  my @cmd = @{ ${args}{command} };

  print "@cmd\n" if ($args{verbose});

  system (@cmd) 
    and die ("Command `@cmd' failed\n");
}

sub davaiRunCommand
{
  my %args = @_;
  my @cmd = @{ ${args}{command} };

  print "@cmd\n" if ($args{verbose});

  my $profile = $args{profile} || 'davai_profile';

  $profile = "$HOME/.$profile";
  die unless (-f $profile);

  my $venvCommand = -f "venv/bin/activate" ? "source ./venv/bin/activate;" : "";

  my $out = `set -e ; source $profile > /dev/null 2>&1; $venvCommand @cmd`;
  my $c = $?;

  print $out if ($args{verbose});

  $c && die ("Davai command `@cmd' failed\n");

  return $out;
}

sub davaiNewXp
{
  my %args = @_;

  my $build = $args{build};

  if (-f $build->getIALGitFile ('davai/bin/new_xp.py'))
    {
      return &davaiNewXpNew (%args);
    }
  else
    {
      return &davaiNewXpOld (%args);
    }

}

sub davaiNewXpNew
{
  my %args = @_;

  my $build = $args{build};

  my $branch = $build->getBranch (%args);
  my $commit = $build->getCommit (%args);

  my $out = &davaiRunCommand (command => [
                                            $build->getIALGitFile ('davai/bin/new_xp.py'),
#                                           '-e',                                                        # Editable
                                            -c => "$branch:$commit",                                     # Comment (will appear in web interface)
                                          ], 
                              davai_profile => 'davai_profile.new',
                              %args);
  my ($nrv) = ($out =~ m/=> (\S+)/goms);

  unless ($nrv) # davai/2
    {
      ($nrv) = ($out =~ m/XP path created : (\S+)/goms);
    }
  
  return $nrv;
}

sub davaiNewXpOld
{
  my %args = @_;

  my $build = $args{build};

  my $branch = $build->getBranch (%args);
  my $commit = $build->getCommit (%args);

  my $out = &davaiRunCommand (command => [
                                            'davai-new_xp', 
#                                           '-e',                                                        # Editable
                                            -v => $args{version},                                        # Version of tests
                                            ($args{origin} ? ('--origin' => $args{origin}) : ()),        # Location of davai repository
                                            -c => "$branch:$commit",                                     # Comment (will appear in web interface)
                                            $branch,
                                          ], 
                              %args);
  my ($nrv) = ($out =~ m/=> (\S+)/goms);

  unless ($nrv) # davai/2
    {
      ($nrv) = ($out =~ m/XP path created : (\S+)/goms);
    }
  
  return $nrv;
}

sub slurp
{
  my $f = shift;
  my $fh = 'FileHandle'->new ("<$f"); 
  die ("Could not open `$f' for reading\n") unless ($fh);
  local $/ =  undef; 
  my $text = <$fh>;
  return $text;
}

sub swapLink
{
  my $f = shift;
  $f = 'File::Spec'->rel2abs ($f);
  return unless (-l $f);
  my $g = readlink ($f);
  unlink ($f);
  rename ($g, $f);
  symlink ($f, $g);
}

sub center
{
  my ($s, $n) = @_; 
  my $i = 0;
  while (length ($s) < $n) 
    {   
      $s = $i % 2 ? " $s" : "$s ";
      $i++;
    }   
  return $s; 
}

sub colorStatus
{
  my $text = shift;
  (my $status = $text) =~ s/(?:^\s*|\s*$)//go;

  my %color = 
  (
    KO                => 'black on_red',
    OK                => 'green',
    '(C...)'          => 'black on_yellow',
    '(I...)'          => 'yellow',
    'X:R?'            => 'black on_red',
    'X'               => 'black on_red',
    'E'               => 'green',
    '!'               => 'black on_red',
    '?'               => 'black on_red',
  );

  if ((-t STDOUT) && (my $color = $color{$status}))
    {
      return &colored (["$color"], $text);
    }
  else
    {
      return $text;
    }
}

sub cancelDavai
{
  my %args = @_;
  my $nrv = $args{nrv};

  my $conf = &davai::getConf (nrv => $nrv);
  
  my $dir = &davai::getMtoolRoot (conf => $conf);

  my $summaries_stack = "$dir/summaries_stack";

  my @task = sort &uniq (map { &basename ($_, qw (.itself.json)) } <$summaries_stack/*.itself.json>);

  for my $task (@task)
    {
      my $f = "$summaries_stack/$task.itself.json";
      my $x = &JSON::decode_json (&slurp ($f));

      my $MTOOL_STEP_DEPOT = $x->{Context}{MTOOL_STEP_DEPOT};
      my @step = <$MTOOL_STEP_DEPOT/step.*.out>;
      
      my %id;
      for my $step (@step)
        {
          my $text = &slurp ($step);

          if (my ($id) = ($text =~ m/SLURM_JOBID="(\d+)"/goms))
            {
              $id{$id} = 1;
            }

          if (my ($id) = ($text =~ m/Submitted batch job (\d+)/goms))
            {
              $id{$id} = 1;
            }
        }

      for my $id (sort keys (%id))
        {
          &runCommand (command => ['scancel', $id], %args);
        }

      unlink ($f);
    }
  
  for my $d (<$dir/*>)
    {
      next if (&basename ($d) eq 'summaries_stack');
      next if (&basename ($d) =~ m/^pack2bin\./o);
      &rmtree ($d);
    }
}

sub getTestCases
{
  my %args = @_;
  my $nrv = $args{nrv};

  my @list = split (m/\n/o, &davaiRunCommand (command => ['davai-run_tests', '-l'], %args));
 
  return @list;
}

sub listTestCases
{
  my %args = @_;
  my $nrv = $args{nrv};

  my @list = &getTestCases (%args);

  for (@list)
    {
      print "$_\n";
    }
}

sub runTestCases
{
  my %args = @_;
  my $nrv = $args{nrv};

  if (my @filter = @{ $args{filter} })
    {
      my @list = &getTestCases (%args);

      for my $test (@list)
        {
          my $ok = 0;
          for (@filter)
            {
              $ok ||= ($test =~ m/$_/i);
            }
          &davaiRunCommand (command => ['davai-run_tests', $test], %args) if ($ok);
        }
    }
  else
    {
      my $conf = &davai::getConf (nrv => $nrv);
      
      my $dir = &davai::getMtoolRoot (conf => $conf);

      my $summaries_stack = "$dir/summaries_stack";

      unlink ($_) for (<$summaries_stack/*>);

      &davaiRunCommand (command => ['davai-run_tests'], %args);
    }
}

sub showStatus
{
  my %args = @_;
  my $nrv = $args{nrv};

  my $conf = &davai::getConf (nrv => $nrv);
  
  my $dir = &davai::getMtoolRoot (conf => $conf) . '/summaries_stack';

  use List::Util qw (uniq max);
  
  my @suff = qw (.itself.json .consistency.json .continuity.json);
  my @task = sort &uniq (map { &basename ($_, @suff) } <$dir/*.json>);

  return unless (@task);

  my $len = &max (map { length ($_) } @task);
  

  printf ("| %-${len}s ", "");
  for my $suff (@suff)
    {
      (my $s = $suff) =~ s/(?:^\.|\.json$)//go;
      printf (" | %20s ", &center ($s, 20));
    }
  printf ("| \n");


  for my $i (0 .. $#task)
    {
      my $task = $task[$i];
      my $line = '';

      $line .= sprintf ("| %-${len}s ", $task);

      for my $suff (@suff)
        {
          my $f = "$dir/$task$suff";
          unless (-f $f)
            {
              $line .= sprintf (" | %20s ", "");
              next;
            }
          my $x = &JSON::decode_json (&slurp ($f));

          if (my $status = $x->{comparisonStatus}{symbol} || $x->{Status}{symbol})
            {
              my $st = stat ($f);
              my $dt = strftime ('%Y-%m-%d %H:%M:%S', localtime ($st->mtime ()));
              $line .= sprintf (" | %20s ", &colorStatus (&center ($status, 20)));
            }
          else
            {
              $line .= sprintf (" | %20s ", "");
            }
        }

      $line .= sprintf ("|\n");

      if ($i % 4 == 0)
        {
          $line =~ s/ /_/go;
        }

      print $line;
    }


# {Listings}{"Compare listings at uri(s)"}{ref}
# {Listings}{"Compare listings at uri(s)"}{test}

}

my $build = 'davai::build'->new ();

my %opts = (version => $build->getVersion (), filter => '');
my @opts_f = qw (verbose dryrun help reuse status cancel dumper versions list);
my @opts_s = qw (version filter origin reference);

sub help
{
  print "Usage: " . &basename ($0) . "\n" 
      . " Options:\n" . join ('', map { "   --$_\n" } @opts_f, @opts_s);
}

if (-f '.davpack.conf')
  {
    unshift (@ARGV, @{ do './.davpack.conf' });
  }

&GetOptions
(
  (map { ($_, \$opts{$_}) } @opts_f),
  (map { ("$_=s", \$opts{$_}) } @opts_s),
);

$opts{reuse} ||= $opts{status};
$opts{reuse} ||= $opts{cancel};
$opts{reuse} ||= $opts{list};

if ($opts{help})
  {
    &help (); 
    exit (0);
  }

$opts{filter} = [split (m/,/o, $opts{filter})];

if ($opts{versions})
  {
    &runCommand (command => [qw (git ls-remote --tags https://github.com/ACCORD-NWP/DAVAI-tests.git)]);
    exit (0);
  }

$opts{build} = $build;

unless (-f $build->getIALGitFile ('davai/bin/new_xp.py'))
  {
    die ("No version of tests was found\n")
      unless ($opts{version});
  }


my $dv;

if ($opts{reuse} && (my @dv = sort <dv-*>))
  {
    $dv = $dv[-1];
  }
else
  {
    my $nrv = &davaiNewXp (%opts);
    
    my @nrv = split (m,/,o, $nrv);
    shift (@nrv) unless ($nrv[0]);

    my ($xppath) = ('');

    for my $p (@nrv)
      {
        $xppath = "$xppath/$p";
        if ($p =~ m/^dv-\d+/o)
          {
            $dv = $p;
            last;
          }
      }

    symlink ($xppath, $dv);
#   &swapLink ($dv); # davai/2

    if ($opts{dumper})
      {
        my $dvpath = 'File::Spec'->rel2abs ($dv);

        my $dumper = "$Bin/davpack-dumper";
        my $dumperConf = "$dvpath/mpiauto.DUMPER.conf";

        my $opts =
        {
          opts =>  
            {   
              'prefix-mpirun' => ['=', [$dumper, '--path', $dvpath, '--']],
            },  
        };

        local $Data::Dumper::Terse = 1;
        'FileHandle'->new (">$dumperConf")->print (&Dumper ($opts));

        my $confPath = &davai::getConfPath (nrv => $nrv);
  
        my $text = &slurp ($confPath);

        $text =~ s/(MPIAUTOCONFIG[ ]*)=[ ]*.*?\n/$1=$dumperConf\n/gos;

        'FileHandle'->new (">$confPath")->print ($text);
      }

    if ($opts{reference})
      {
        my $conf = "$dv/davai/nrv/conf/davai_nrv.ini";
        my $text = do { my $fh = 'FileHandle'->new ("<$conf"); local $/ = undef; <$fh> };
        for ($text)
          {
            s/^(ref_xpid\s+=\s*)(\S+)$/$1$opts{reference}/gm;
            s/^(ref_vconf\s+=\s*)(\S+)$/${1}nrv/gm;
          }
        'FileHandle'->new (">$conf")->print ($text);
      }

  }

die unless ($dv);

my $nrv = 'File::Spec'->rel2abs ("$dv/davai/nrv");

my @build = $build->getBuilds (nrv => $nrv);

unless ($opts{dryrun} || $opts{status} || $opts{cancel} || $opts{list})
  {
    # Check all pack are at the same commit

    my %commit;
    for my $build (@build)
      {
        $commit{$build} = $build->getCommit ();
      }

    if (grep { $commit{$build} ne $commit{$_} } @build)
      {
         for my $build (@build)
           {
             printf (" %s %s\n", $commit{$build}, $build);
           }
         die ("Commit mismatch\n");
      }

    # Create davai executables if necessary

    for my $build (@build)
      {
        $build->compileBinaries (%opts);
        $build->setBinaryLinks (nrv => $nrv, %opts);
      }
  }

chdir ($nrv);

if (! $opts{reuse})
  {
    &davaiRunCommand (command => ['davai-ciboulai_init'], %opts);
  }

if ($opts{list})
  {
    &listTestCases (%opts, nrv => $nrv);
  }
elsif ($opts{status})
  {
    &showStatus (%opts, nrv => $nrv);
  }
elsif ($opts{cancel})
  {
    &cancelDavai (%opts, nrv => $nrv);
  }
elsif (! $opts{'dryrun'})
  {
    &runTestCases (%opts, nrv => $nrv);
  }



